name: Run test 

env:
  OS: ubuntu-latest
  
on: push

jobs:
  install_dependency_run_test_and_get_allure_report:
    runs-on: ubuntu-latest
    steps:
      - name: "Скачиваем селенойд"
        run: curl -s https://aerokube.com/cm/bash  | bash
        
      - name: "Даем права на запуск селенойда"
        run: chmod +x ./cm
        
      - name: "Запускаем selenoid"
        run: ./cm selenoid start --vnc
        
      - name: "Запускаем selenoid-ui"
        run: ./cm selenoid-ui start
        
      - name: "Используем main репозиторий"
        uses: actions/checkout@v1
        
      - name: "Запускаем тесты"
        if: always()
        run: mvn clean test
        continue-on-error: true        
        
      - name: "Генерируем аллюр-репорт"
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          
      - name: "Пушим аллюр-репорт в ветку allure_reports"
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: allure_reports
          PUBLISH_DIR: allure-history
